### ISSUE TITLE
copy pasted code

### ISSUE THREAD

**Issue by Karyum** [WebAhead8/AgencyProj#6]
it's fine to copy paste code literally every developer does it, but please make sure that you understand the code before you add it.

PS: *I think I can find the link where you copy pasted the flip card 😆*

**Comment by MaySaadi** [comment]
> it's fine to copy paste code literally every developer does it, but please make sure that you understand the code before you add it.
> 
> PS: _I think I can find the link where you copy pasted the flip card 😆_

I
